# Generated by Django 4.2.16 on 2024-11-21 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
