# Generated by Django 4.2.16 on 2024-12-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchHistory',
        ),
    ]
